# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lge/joan/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/lge/joan

PRODUCT_COPY_FILES += \
    vendor/lge/joan/proprietary/vendor/etc/wifi/bdwlan.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdwlan.bin \
    vendor/lge/joan/proprietary/vendor/etc/wifi/bdwlan_ch0.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdwlan_ch0.bin \
    vendor/lge/joan/proprietary/vendor/etc/wifi/bdwlan_ch1.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdwlan_ch1.bin \
    vendor/lge/joan/proprietary/vendor/firmware/H930/a540_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/H930/a540_zap.b00 \
    vendor/lge/joan/proprietary/vendor/firmware/H932/a540_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/H932/a540_zap.b00 \
    vendor/lge/joan/proprietary/vendor/firmware/H930/a540_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/H930/a540_zap.b01 \
    vendor/lge/joan/proprietary/vendor/firmware/H932/a540_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/H932/a540_zap.b01 \
    vendor/lge/joan/proprietary/vendor/firmware/H930/a540_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/H930/a540_zap.b02 \
    vendor/lge/joan/proprietary/vendor/firmware/H932/a540_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/H932/a540_zap.b02 \
    vendor/lge/joan/proprietary/vendor/firmware/H930/a540_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/H930/a540_zap.elf \
    vendor/lge/joan/proprietary/vendor/firmware/H932/a540_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/H932/a540_zap.elf \
    vendor/lge/joan/proprietary/vendor/firmware/H930/a540_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/H930/a540_zap.mdt \
    vendor/lge/joan/proprietary/vendor/firmware/H932/a540_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/H932/a540_zap.mdt \
    vendor/lge/joan/proprietary/vendor/lib/libpn548ad_fw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpn548ad_fw.so \
    vendor/lge/joan/proprietary/vendor/lib64/libpn548ad_fw_64.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpn548ad_fw_64.so

PRODUCT_PACKAGES += \
    bdwlan_bdwlan_symlink \
    bdwlan_ch0_bdwlan_ch0_symlink \
    bdwlan_ch1_bdwlan_ch1_symlink
